name: 01 - Building Blocks
on: push
    # push:
    #     branches: main
jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps: 
          -  name: say hello
             run: echo "Hello World!"
    echo-goodby:
        runs-on: ubuntu-latest
        steps:
          - name: Succesful steps
            run: |
              echo "i will succeeds"
              exit 0
          - name: say bay
            run: echo "Good Bye!"

 